### ISSUE TITLE
Toki roadmap

### ISSUE THREAD

**Issue by purifetchi** [purifetchi/Toki#1]
# Missing Toki features

This list is just some of the features I think Toki should have to at least be somewhat useable.

- [ ] Profile customization
	- [ ]  Avatar editing
	- [ ] Banner editing
	- [ ] Display name
	- [ ] Bio
	- [ ] Profile links
	- [ ] Featured posts
- [ ] Posts
	- [ ] Attaching media via MastoAPI
	- [ ] Polls
	- [ ] Quote posts
	- [ ] Emoji reactions
	- [ ] Parsing messages before sending
		- [ ] Linking to profiles on mention
		- [ ] Emoji support
- [ ] ActivityPub conformance
	- [ ] Support for Undo activities
		- [ ] Create
		- [ ] Follow
	- [ ] Support for Update activities
		- [ ] Note
		- [ ] Actor
- [ ] Instance customization
	- [ ] Implement a nodeinfo endpoint for the instance
	- [ ] Implement the ability to set an instance banner
	- [ ] Implement the ability to set an instance icon
	- [ ] Make the database endpoint configurable
	- [ ] Make the redis endpoint configurable
	- [ ] Somehow fetch the current Toki version
	- [ ] Custom emojis

**Comment by popovics00** [comment]
I am interested in assisting with this task, could you provide me with a more detailed description of the tasks

**Comment by purifetchi** [comment]
the list is quite expansive and varied, but if there's something specific from it that interests you, i can explain it in detail :)

**Comment by popovics00** [comment]
Do you perhaps have Skype or Telegram to expedite communication? If not, it's okay, we can also use GitHub.

**Comment by purifetchi** [comment]
i don't have either of these, sorry

(also sorry for the response, i was busy these past few days)

**Comment by popovics00** [comment]
if you want I can work on the design (to do a redesign) since I see that you are not good with it or give me a description for the post feature, the remaining items that have not been done?

**Comment by purifetchi** [comment]
Hi, sorry, had some work this week so I couldn't get back to you.

The remaining items for Posts are the implementation of Polls, which ActivityPub Question types, according to how Mastodon does them: https://humberto.io/blog/mastodon_poll_in_activitypub/. We need the ability to be able to import remote question types into the database (create the model, hook it up to the Post model), parse the incoming ASQuestion types and replies. Also implementing the mastodon API endpoints for creating them: https://docs.joinmastodon.org/methods/polls/.

The implementation of quote posts is a bit more tricky because there isn't a single defined implementation (software like Akkoma and Misskey do it both in a different way), so I can't really get too deep into it.

Lastly emoji reactions require us to somehow store the incoming ASEmojiReact types into the inbox in the Post, and display them on the frontend. I didn't do much research yet into how Pleroma or Misskey do it, but if needed I can provide more info.

The roles task basically requires us to make a small Role model and attach it to the Credentials model, in which we can specify whether what the user can do. Edit emojis, remove posts, handle blocks. This won't do much for now but as I work on the admin frontend and API it will come in handy.

**Comment by popovics00** [comment]
I need instructions on how to run the program, does it have a front end, because I can't find my way around your code.
