### ISSUE TITLE
Administration roadmap

### ISSUE THREAD

**Issue by purifetchi** [purifetchi/Toki#11]
Some of the things that have to be done in order to make administrating Toki actually viable:

- [ ] Add a role system
    - [ ] Create an admin role by default
    - [ ] Allow creating custom roles (each having their own set of permissions)
- [ ] Create an admin panel (akin to pleroma's/akkoma's admin-fe)
